---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  
verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[filebeat_cookbook_v2::default]
    attributes:
